
# ------------------------------------------------------------------------------
# Script: DR_analysis.R
#
# This script performs downstream analysis and visualization of drug repurposing
# results generated by the processing step. It loads RData result files,
# extracts drug hits and disease signatures, and filters them against CMAP
# metadata for valid instances. The workflow includes plotting score
# distributions, generating drug–disease reversal heatmaps, creating overlap and
# UpSet plots across datasets, and exporting summary tables. Together, these
# outputs provide a comparative view of candidate drug hits and their
# consistency across multiple fibroid signature datasets.
# ------------------------------------------------------------------------------


# Load required libraries
library(dplyr)       # data wrangling
library(gplots)      # plotting (venn, heatmaps, etc.)
library(reshape2)    # data reshaping (melt, dcast)
library(pheatmap)    # heatmap plotting
library(UpSetR)      # UpSet plots for set intersections
library(grid)        # low-level graphics system
library(DRpipe)      # your custom pipeline functions

# Set up output directories
dir.out <- "results/analysis/"
dir.create(dir.out)  # create analysis results directory
dir.out.img <- paste0(dir.out, "img/")
dir.create(dir.out.img)  # create subdirectory for images

# Load all pipeline results stored as RData files
files <- list.files(path = "results/", pattern = "CoreFibroid_logFC")
results <- lapply(files, function(f){
    load(paste0("results/", f))  # each file contains 'results' object
    res <- results
    return(res)
})
names(results) <- sub("(.*).RData", "\\1", files)  # name each list element by filename

# Extract drug prediction results (res[[1]])
drugs <- lapply(results, function(res){
    # res[[1]] contains cmap score, p-values, q-values
    res[[1]]
})

# Extract disease signature results (res[[2]])
dz_signatures <- lapply(results, function(res){
    # res[[2]] contains gene IDs and log fold changes (logFCs)
    res[[2]]
})

# Tag each drug dataset with its comparison ID
for (x in names(drugs)) {
    drugs[[x]]$subset_comparison_id <- x
}

# Plot histograms of reversal scores for all drug sets
pl_hist_revsc(drugs, save = "dist_rev_score.jpeg", path = dir.out.img, width = 1500)

# Read CMAP experiment metadata and validation sets
cmap_experiments <- read.csv("data/cmap_drug_experiments_new.csv", stringsAsFactors = FALSE)
valid_instances  <- read.csv("data/cmap_valid_instances.csv", stringsAsFactors = FALSE)

# Merge and filter only valid experiments with DrugBank IDs
cmap_experiments_valid <- merge(cmap_experiments, valid_instances, by = "id")
cmap_experiments_valid <- subset(cmap_experiments_valid, valid == 1 & DrugBank.ID != "NULL")

# Filter drug hits using the valid experiment metadata
drugs <- lapply(drugs, function(x){ valid_instance(x, cmap_experiments_valid) })

# Write filtered results to CSV for each dataset
for(n in names(drugs)){
    if(nrow(drugs[[n]] != 0)){
        write.csv(drugs[[n]], file = paste0(dir.out, n, "_hits.csv"))
    }
}

# Load CMAP reference signatures for heatmap comparison
load('data/cmap_signatures.RData')

# Prepare and export combined drug–disease signature tables
for(n in names(drugs)){
    if(nrow(drugs[[n]] != 0)){
        drug_dz_sig <- prepare_heatmap(drugs[[n]], dz_sig = dz_signatures[[n]], cmap_signatures)
        write.csv(drug_dz_sig, file = paste0(dir.out, n, "_drug_dz_signature_all_hits.csv"))
    }
}

# Example: run prepare_heatmap for a single dataset
# drug_dz_sig <- prepare_heatmap(drugs$CilEpi_PE, dz_sig = dz_signatures$CilEpi_PE, cmap_signatures)
# write.csv(drug_dz_sig, file = paste0(dir.out, "Endo_PE", "drug_dz_signature_all_hits.csv"))

# Plot heatmaps of drug–disease signature reversal
for(n in names(drugs)){
    pl_heatmap(drugs[[n]], dz_signatures[[n]], cmap_signatures, n,
               width = 12, height = 10, units = "in",
               save = "heatmap_cmap_hits.jpg")
}

# Example: plot a single dataset heatmap
# pl_heatmap(drugs_se$Endo_SE, dz_signatures$Endo_SE, cmap_signatures, "Endo_PE",
#            width = 12, height = 10, units = "in")

# Combine all drug results across datasets
drugs_integrated <- do.call("rbind", drugs)

# Plot overlap of hits across datasets
pl_overlap(drugs_integrated, save = "hits_overlap_heatmap.jpg")
pl_overlap(drugs_integrated, at_least2 = TRUE, width = 7,
           save = "hits_overlap_atleast2_heatmap.jpg")

# Prepare UpSet plot input and plot intersections
ls <- prepare_upset_drug(drugs_integrated)
pl_upset(ls, save = "upset.jpg")

# View detailed overlaps using a Venn diagram
p   <- venn(ls, show.plot = FALSE)
int <- attributes(p)$intersections
int$`CoreFibroid_logFC_0.5:CoreFibroid_logFC_1.5:CoreFibroid_logFC_1`  # inspect specific intersection


